name: Health check
on:
  workflow_call:
  

permissions:
  contents: read # for checkout
      
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    permissions:
      contents: read    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm clean-install
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Check code format
        run: npm run format:check
      - name: Lint code
        run: npm run lint
      - name: Run tests
        run: npm test      
